""" 
This is the Snakefile that runs the analysis for SARS-CoV-2_chronic_infection_seq.

Author: Will Hannon – https://www.linkedin.com/in/williamhannon/
"""

#### ----------------------- Imports ----------------------- ####

import pandas as pd 
from os.path import join
from snakemake.utils import min_version

min_version('5.6.0')  # require `snakemake` >= 5.6.0

#### -------------------- Configuration -------------------- ####

configfile: "config/config.yml"

#### ------------------------ Utils ------------------------ ####

include: "rules/common.smk"

#### ----------------------- Targets ----------------------- ####

rule all:
    input: 
        join(config['figure_dir'], "rbd_escape_mutations.svg"),
        join(config['figure_dir'], "all_spike_mutations.svg"),
        join(config['figure_dir'], "coverage_over_spike.svg"),
        join(config['figure_dir'], "phased_rbd_mutations.svg"),
        join(config['qc_dir'], 'multiqc'),
        join(config['variant_dir'], "variants.csv"),
        join(config['pileup_dir'], "samtools_variants.csv")
        

        
rule clean:
    shell:
        """
        rm -rf logs/
        rm -rf tmp/
        rm -f slurm*.out
        """
#### ------------------------ Rules ------------------------ ####

include: "rules/download-reference.smk"
include: "rules/download-tools.smk"
include: "rules/download-fastq.smk"
include: "rules/index-reference.smk"
include: "rules/trim-adapters.smk"
include: "rules/filter-reads.smk"
include: "rules/align-reads.smk"
include: "rules/calculate-coverage.smk"
include: "rules/calculate-pileup.smk"
include: "rules/qc-tools.smk"
include: "rules/call-variants.smk"
include: "rules/make-figures.smk"
